Add Reminders in React
HyphaApp/hypha pull request #2334
Opened 2021-04-16 06:28 UTC by vimal1083

Fixes #2247 

https://user-images.githubusercontent.com/8245654/114980981-e8112a00-9eaa-11eb-8b77-c1b12c946391.mp4

If reminder created in Django, it will appear as "untitled reminder" in react

https://user-images.githubusercontent.com/8245654/114981056-024b0800-9eab-11eb-9dbf-63f034438df8.mp4

2021-04-16 08:42 UTC, frjo requested changes
Works as it should but have some things I want changes and added.

* The date picker should use ISO 8601 (or if possible adapt to the users/browser locale).
* The "Assign" select field in the Reminder popup uses the keys and not the values as choices.

Also the new fields etc. for reminders should be added to the Django side of the Reminder UI as well. We also need to work on the backend for sending the extended reminders. But that is coming I assume since this is a draft still.

2021-04-16 08:42 UTC, frjo commented on hypha/apply/funds/models/utils.py
> +class CustomerTypes(Enum):
UserTypes is better term I think.

2021-04-16 08:42 UTC, frjo commented on hypha/static_src/src/app/src/containers/DisplayPanel/index.js
> +            <ReminderContainer submissionID={submissionID}/>
Move this below screening.

2021-04-20 06:31 UTC, Parbhat commented
@frjo Going the requirements of the feature and it seems that we can skip the suggested [assign](https://github.com/HyphaApp/hypha/issues/1943#issue-604035180) field for now. As not sure how it will be used. Currently, we have an [action](https://github.com/HyphaApp/hypha/blob/a256a25c832fcb9f2bf0b37c4449ac9c86222a70/hypha/apply/funds/models/reminders.py#L30) field that helps to pick the reminder purpose. So, for now, we can replicate the Reminder feature from Django in React app + new fields like Title, description added to both + some other improvements. Sounds ok?

2021-04-21 06:46 UTC, vimal1083 commented
@frjo Now we have title and description for a reminder, Do you add this information in reminder e-mail?

2021-04-21 07:19 UTC, Parbhat commented
@vimal1083 It would be good to have the new info in email as well.

2021-04-26 08:24 UTC, Parbhat commented
@frjo We can deploy it to test.

2021-05-18 12:34 UTC, frjo requested changes
I have removed the time part from reminders in the Django side (only changed widget, not db field), can you do the same for the React side? Then I can get this merged. Nice work!

2021-05-18 13:23 UTC, vimal1083 commented
@frjo yeah, updated in React

2021-05-18 13:33 UTC, frjo approved these changes

2021-05-19 11:22 UTC, v1k45 requested changes
Looking good, a few nitpicks and suggestions:

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/index.js
> +                            </>
Is the fragment block necessary here?

There is only a single component inside `Modal`, we can directly place `ReminderForm` here.

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/index.js
> +withStyles(styles)
Style nitpick:

These lines should be indented.

```suggestion
    withSaga,
    withReducer,
    withConnect,
    withRouter,
    withStyles(styles)
```

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/actions.js
> +})
Style nitpick:

These two functions have inconsistent indentation. It is indented using tab where as other parts in the part have 2-space indentation.

Same with other occurrences in the changeset.

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/index.js
> +            <div className="reminder-container">
What do you think about moving the <LoadingPanel /> outside the main `return` block.

We can put an early-return to avoid nested contions.

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/selectors.js
> +      const index = reminders.indexOf(reminders.find(r => r.grouper == reminder.action_type))
We are looping over `reminders` 3 times.

What do you think about using `findIndex` to cut down the loops?

Something like:

```js
const existingReminderIndex = reminders.findIndex(r => r.grouper == reminder.action_type);
// reminder is found.
if (existingReminderIndex != -1) {
  reminders[existingReminderIndex].list.push(reminder)
} else {
  // new reminder.
  reminders.push({ grouper: reminder.action_type, list: [reminder] })
}
```

2021-05-19 11:22 UTC, v1k45 commented on hypha/static_src/src/app/src/containers/ReminderContainer/index.js
> +                        <ReminderList
Style Nitpick:

We can make this block more easier to read by extracting `this.props.reminders || []`  to a separate variable and then using it here without the extra condition.

Also, it is possible for `reminders` be to anything other than a list after it is loaded?

2021-05-19 13:27 UTC, vimal1083 commented on hypha/static_src/src/app/src/containers/ReminderContainer/index.js
> +                            </>
Without this Fragment, there will be a warning message because of material UI bug. By adding this fragment, it got resolved

2021-05-20 14:43 UTC, v1k45 approved these changes
Nice work! LGTM :+1:

2021-05-21 06:34 UTC, merged