fix: Project table filter's broken dropdown
HyphaApp/hypha pull request #2402
Opened 2021-05-31 13:54 UTC by sandeepsajan0

Fixes #2388

As I left a [comment](https://github.com/HyphaApp/hypha/issues/2388#issuecomment-851174374) in the issue, these were getting overwritten because of their same names for django-filter. I tried to look into its templates code as well but I found this clue via its html(inspect, select's id and name).

Broken Filters Behaviour:
![image](https://user-images.githubusercontent.com/23638629/120203387-491b7400-c245-11eb-8e09-35ca4cbd4c90.png)

Fixed Behaviour:
![image](https://user-images.githubusercontent.com/23638629/120203804-b8916380-c245-11eb-8a19-fc0cd24fb863.png)

2021-05-31 21:07 UTC, sks444 commented on hypha/apply/projects/filters.py
> +    project_status = Select2MultipleChoiceFilter(label='Status', choices=PROJECT_STATUS_CHOICES)
@sandeepsajan0, this fixes the ui but breaks the filter functionality, as these fields are not model fields anymore. We may need to use [to_field_name](https://django-filter.readthedocs.io/en/stable/ref/filters.html#to-field-name) param here.

2021-05-31 21:29 UTC, sks444 requested changes
@sandeepsajan0, given that filter fields with similar `id` and `name` is the cause of the problem. It would be interesting to know how this html id and name is being generated for that field? Is it coming from django-filter package itself?

I think a stable solution for this would be to have `id` and `name` generated with the set model name prefix. E.g. in our case,  for status field on project filter which has project model set, id could be `project-status` instead of just `status`.  So that no two filters on the same page have same id/name.

If it's coming from the filter package, maybe we can open an issue there, describing the steps to reproduce it.

Until then I think that our fix does the work.

2021-06-02 11:10 UTC, sks444 approved these changes
Looks good.

2021-06-02 11:16 UTC, sks444 commented
We did some research on others ways(https://github.com/HyphaApp/hypha/pull/2402#pullrequestreview-672543803) to avoid this problem. Which looks complicated, so going with renaming the filter fields for now.

2021-06-02 13:21 UTC, frjo approved these changes
Excellent work! Nice and clean fix.

2021-06-02 13:21 UTC, merged