Fix Review visibility and use exclude for existing data
HyphaApp/hypha pull request #2466
Opened 2021-08-02 13:41 UTC by sandeepsajan0

Fixes #2461 

1. Change Visibility of reviews' activity(action) according to reviews visibility.
2. Exclude/Hide the New Review activity for Applicant.

2021-08-04 18:55 UTC, frjo commented
@sandeepsajan0 Is it not possible to reuse the "visibility" value that we already use for comments? Setting it to "reviewers" and making sure the view respect it should fix the issue.

2021-08-05 10:37 UTC, sandeepsajan0 commented
@frjo Yes, It is possible but it will only work for new data. For existing data, we will need these changes.

2021-08-05 11:08 UTC, frjo commented on hypha/apply/activity/models.py
> +        # To hide reviews from the applicant's activity feed
Add a TODO about this is just for historic data and not needed for new data efter this.

2021-08-05 11:12 UTC, frjo commented
I think we can do both in this PR.

Looking at this it I realise it should effect both MESSAGES.NEW_REVIEW and MESSAGES.REVIEW_OPINION.

Can you add code that set these two actions to visibility "reviewers"? Thanks!

Later on I can create a SQL call that sets visibility to "reviewers" for all historic data as well, then we can remove the custom code.

2021-08-05 11:13 UTC, frjo requested changes

2021-08-05 11:13 UTC, frjo commented on hypha/apply/activity/models.py
> +                message=messages.get(MESSAGES.NEW_REVIEW)
Please add MESSAGES.NEW_REVIEW and MESSAGES.REVIEW_OPINION.

REVIEW_OPINION is a type of lightweight review.

2021-08-05 11:40 UTC, sandeepsajan0 commented
Sure, I'll make the changes.

In review, we have two types of visibility `private` and `reviewers`. If we will have only `reviewers` visibility in activities then it may leads to reviewer's activity feed issue. So, It would be better if we assign `Team` for `private` visiblity and `reviewers` for `reviewers`. What do you think?

2021-08-06 07:34 UTC, frjo commented
@sandeepsajan0 The code already adds "team" to MESSAGES.REVIEW_OPINION actions, sorry I did not notice this before. 

So the question id then if MESSAGES.NEW_REVIEW should be set to "team" or "reviewers". Asking @fourthletter this.

2021-08-06 07:37 UTC, frjo commented
@sandeepsajan0 Got a reply from @fourthletter, only staff should see MESSAGES.NEW_REVIEW so please set visibility to "team" (not "reviewers" as I wrongly stated above.)

You can then add MESSAGES.NEW_REVIEW to the list at https://github.com/HyphaApp/hypha/blob/45a5cb5eba94e95310f5251c7eb555e341c9e061/hypha/apply/activity/messaging.py#L259-L269

2021-08-06 09:36 UTC, fourthletter commented
Thank you @sandeepsajan0  for working on this and following up. 

@frjo Thank you for reaching out because I didn't fully scope out this issue. External Reviewers 1) do not need to see when a review has been submitted because reviews should be anonymous and 2) there is no value in having extraneous items in their activity feed, this info would only add more clutter.

2021-08-09 08:28 UTC, frjo approved these changes

2021-08-09 08:31 UTC, frjo commented
Deployed to test now.

2021-08-12 08:05 UTC, merged