Use FILE_ALLOWED_EXTENSIONS to validate form upload documents
HyphaApp/hypha pull request #2498
Opened 2021-08-20 10:40 UTC by sandeepsajan0

Related to [hypha-issues/2](https://github.com/HyphaApp/hypha-issues/issues/2)

2021-08-23 09:39 UTC, frjo requested changes
This works nicely client side. We would need a check on the backend as well before saving the form.

2021-08-23 09:39 UTC, frjo commented on hypha/public/forms/models.py
> +        return FileField(widget=FileInput(attrs={'accept': settings.FILE_ACCEPT_ATTR_VALUE}), **options)
I changed to FILE_ACCEPT_ATTR_VALUE so the formatting gets correct for the accept attribute.

2021-08-23 12:43 UTC, sandeepsajan0 commented
We are already having these validations on file fields(on both Multi and Single FileField). These are checking the forms before saving. https://github.com/HyphaApp/hypha/blob/main/hypha/apply/stream_forms/fields.py#L51

@frjo Where else do you think we need it?

2021-08-23 12:46 UTC, frjo commented
The "Forms" are not using the uploads field from stream forms but a custom solution. So somewhere here maybe.

https://github.com/HyphaApp/hypha/blob/main/hypha/public/forms/models.py#L73-L93

2021-08-24 06:25 UTC, frjo commented
Rebased to get in some fixes so test run as they should.

2021-12-07 16:36 UTC, sandeepsajan0 commented
@frjo I have tried to add validation in backend with custom clean method in form builder. Let me if it works good enough.

2021-12-07 19:45 UTC, frjo approved these changes

2021-12-20 19:39 UTC, Erioldoesdesign commented
Can this be merged?

2021-12-21 17:57 UTC, merged