Remove staff reviewers for a submission
HyphaApp/hypha pull request #2547
Opened 2021-09-13 07:48 UTC by sandeepsajan0

Fixes #1575 

Change widget and delete an Assigned Reviewer object if user wants to just unassign that reviewer.
Previously, Select2Widget were look like a checkbox but wasn't an actual checkbox, we were not able to unselect that. 

@frjo "Select a Reviewer" message fine to unassign the reviewer or Should I change it to "-------" or "None"?

2021-09-13 09:07 UTC, frjo commented
@sandeepsajan0 This works well in my testing, nice fix!

"Select a Reviewer" should be changed as you say. @ei8fdb Do you have a good suggestion what to use?

There is also one situation that we need to handle in some way.

If staff reviewers have been selected *and* submitted reviews and we then remove them without setting new ones the submitted reviews are deleted.

Maybe a check so you can only remove reviewers that have not submitted a review?

2021-09-13 09:35 UTC, sandeepsajan0 commented
@frjo Thanks for pointing that out. I'll restrict it to reviewers who haven't submitted review.

2021-09-13 13:30 UTC, sandeepsajan0 commented
@frjo I have filtered the Reviewers who have a review for the same role and submission.
Do we need to add a condition for form error as well? I tried to add form_errors in clean method in my local but wasn't working very well.

2021-09-13 13:44 UTC, frjo requested changes
This works but I think we should display a form error messages about it not being possible to remove, just change, reviewers that have reviews.

As it stands the review removal fails silently if the reviewer has reviews.

2021-09-15 14:16 UTC, frjo commented
@sandeepsajan0 I committed the change that @ei8fdb suggested. And it all works very well now. Just the test that needs updating it seems. Can you take a look at that?

2021-09-16 08:33 UTC, sandeepsajan0 commented
Sure @frjo . I'll fix it.

2021-09-16 10:42 UTC, sandeepsajan0 commented
@frjo I don't know what was the issue. I tried it in my local, it works fine then I just rerun it here and it works. I think there might be some cache issues in CI env.

2021-09-16 11:16 UTC, frjo approved these changes

2021-09-16 11:18 UTC, frjo commented
Excellent, this is now on test for OTF to check out.

2021-09-16 12:18 UTC, merged