Contractor changes for invoice resubmit
HyphaApp/hypha pull request #2640
Opened 2021-11-23 05:12 UTC by chaitu210

Fixes #2619

Add description here.

2021-11-25 09:46 UTC, frjo requested changes
Nice work! Just some translations issue.

P.S. I notice that there are a number of old translations issues in `messaging.py`. I will correct the mistakes (mine) in a separate PR.

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +            invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
F-strings and translations issue here. Use format().

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +            invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
F-strings and translations issue here. Use format().

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +            message_for_pm = '<p>{}</p>'.format(form.cleaned_data['message_for_pm'])
Prefer F-string here.

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +            comment = '<p>{}</p>'.format(form.cleaned_data['comment'])
Prefer F-string here.

2021-11-25 09:46 UTC, frjo commented on hypha/apply/activity/messaging.py
> +        invoice_status_change = _(f'Updated Invoice Info and Status changed to: {invoice.status_display}.')
F-strings and translations issue here. Use format().

2021-11-25 09:46 UTC, frjo commented on hypha/apply/activity/messaging.py
> +        invoice_status_change = _(f'Updated Invoice status to: {invoice.status_display}.')
F-strings and translations issue here. Use format().

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
F-strings and translations issue here. Use format().

2021-11-25 09:46 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                message_for_pm = '<p>{}</p>'.format(form.cleaned_data['message_for_pm'])
Prefer F-string here.

2021-11-29 08:26 UTC, frjo approved these changes

2021-11-29 08:27 UTC, frjo commented
Deployed to test just now.

2021-12-01 13:36 UTC, frjo requested changes

2021-12-01 13:36 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
This seems to have been reverted by mistake.

2021-12-01 13:36 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                message_for_pm = '<p>{}</p>'.format(form.cleaned_data['message_for_pm'])
As have this.

2021-12-01 13:37 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
While you are at it you can remove the extra space before the colon as well, here and in one or two other places as well.

2021-12-01 13:41 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +                invoice_status_change = _(f'<p>Invoice status updated to : {self.object.status_display}. </p>')
As well as space after the last period. It have no effect on the output but un neat stuff like that bothers me :-).

2021-12-01 13:47 UTC, frjo commented on hypha/apply/projects/views/payment.py
> +            message_for_pm = '<p>{}</p>'.format(form.cleaned_data['message_for_pm'])
Reverted here as well.

2021-12-03 13:27 UTC, frjo requested changes

2021-12-03 13:27 UTC, frjo commented on hypha/settings/dev.py
> +    'STATS_FILE': os.path.join(BASE_DIR, r'hypha\static_compiled\app\webpack-stats.json'),
This looks Windows specific?

2021-12-03 13:27 UTC, frjo commented on hypha/settings/dev.py
> +}
This should go in to each developers local.py file I believe.

2021-12-07 21:12 UTC, sks444 approved these changes
Looks good.

@frjo can we deploy this to test again? Thanks!

2021-12-07 21:52 UTC, frjo approved these changes

2021-12-07 21:57 UTC, frjo commented
Deployed to test now.

2021-12-14 16:59 UTC, sks444 commented
@frjo do you think we could merge this in..if all looks good?

2021-12-15 09:15 UTC, merged