Refractor to serve JS locally
HyphaApp/hypha pull request #2932
Opened 2022-07-21 09:25 UTC by theskumar

Fixes: None

Content served CDN is an area of concern for privacy & performance.
Ensure all the JS code is served locally.

- Serve ‘url-search-params.js’ locally.
- Serve ‘symbol-es6.min.js’ locally.
- Serve “jquery.fancybox.min.js" locally.

2022-07-21 09:40 UTC, theskumar commented
I need to look at the lint issues. Do not merge.

2022-07-22 04:02 UTC, theskumar commented on hypha/static_src/src/javascript/apply/url-search-params.js
> +var URLSearchParams=URLSearchParams||function(){"use strict";function URLSearchParams(query){var index,key,value,pairs,i,length,dict=Object.create(null);this[secret]=dict;if(!query)return;if(typeof q
Patching it up with the latest version.

2022-07-23 14:03 UTC, frjo requested changes
Works well in my testing, just one small issue.

2022-07-23 14:03 UTC, frjo commented on hypha/apply/projects/templates/application_projects/overview.html
> +    <script src="https:{% static 'js/apply/jquery.fancybox.min.js' %}"></script>
Quick fix here to remove "https:".

2022-07-24 19:11 UTC, frjo commented
Easy way to get the select2 js and css to also be local?

2022-07-26 08:39 UTC, theskumar commented on hypha/apply/projects/templates/application_projects/overview.html
> +    <script src="https:{% static 'js/apply/jquery.fancybox.min.js' %}"></script>
Good catch, will fix it.

2022-07-26 08:40 UTC, theskumar commented on hypha/apply/projects/templates/application_projects/overview.html
> +    <script src="https:{% static 'js/apply/jquery.fancybox.min.js' %}"></script>
```suggestion
    <script src="{% static 'js/apply/jquery.fancybox.min.js' %}"></script>
```

2022-07-26 09:41 UTC, theskumar commented
> Easy way to get the select2 js and css to also be local?

Are you talking about the `django-select2` package? They do have css/js in their `static` local folder. Would you be able to point me where it's you see them remotely served?

2022-07-26 09:41 UTC, theskumar commented
Other than select2 issue I believe this is good to merge in, I can take a stab at select2 js/css in another PR.

2022-07-27 06:54 UTC, frjo approved these changes

2022-07-27 06:56 UTC, merged