Move SendNoticeBlock to required blocks
HyphaApp/hypha pull request #2980
Opened 2022-09-14 10:53 UTC by sandeepsajan0

Fixes #2460

2022-09-26 06:48 UTC, theskumar approved these changes

2022-09-26 14:01 UTC, frjo commented
The field say "Send_Notice Field", can we get that to be "Send notice Field". Just looks nicer.

![Skärmavbild 2022-09-26 kl  15 59 38](https://user-images.githubusercontent.com/191392/192296014-b05bbef2-e75b-4604-9239-3e85473aa0da.png)

2022-09-26 14:01 UTC, frjo requested changes

2022-09-26 14:01 UTC, frjo commented on hypha/apply/determinations/blocks.py
> +    default_value = BooleanBlock(required=True)
I think this should be `default_value = BooleanBlock(default=True, required=False)`

2022-09-27 10:27 UTC, sandeepsajan0 commented on hypha/apply/determinations/blocks.py
> +    default_value = BooleanBlock(required=True)
I have updated the default_value field as we discussed.

2022-09-27 10:37 UTC, sandeepsajan0 commented
> The field say "Send_Notice Field", can we get that to be "Send notice Field". Just looks nicer.
> 
> ![Skärmavbild 2022-09-26 kl 15 59 38](https://user-images.githubusercontent.com/191392/192296014-b05bbef2-e75b-4604-9239-3e85473aa0da.png)

Yes, we can change it but I think that is a separate issue because I found it at other places as well like full_name field in application forms. It is happening because we are using [name field here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/utils/blocks.py#L192) and name field can't have spaces in it. 
So, a possible solution is we use [Block's meta's label](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/determinations/blocks.py#L59) instead of the name field whenever the label is present.

2022-09-27 12:15 UTC, frjo approved these changes

2022-10-04 08:09 UTC, merged