Latest Project Ui changes
HyphaApp/hypha pull request #3291
Opened 2023-03-20 06:33 UTC by sandeepsajan0

Fixes #3191 and more.

Changes for Latest Project UI:
1. Project documents
2. Contracting documents
3. Remove "Action to take"

2023-03-23 12:05 UTC, sandeepsajan0 commented
@frjo I have fixed the tests, I think we can put this on the test site.

2023-03-24 06:52 UTC, sandeepsajan0 commented
@frjo 'New contract creation every time user uploads a contract' was a short fix so I included it in this PR. I'll create a separate PR for the other improvements and changes.

2023-03-27 11:11 UTC, frjo requested changes
Some minor changes to css.

2023-03-27 11:11 UTC, frjo commented on hypha/static_src/src/sass/apply/components/_data-block.scss
> +        font-weight: 700;
Please use variables from `_variables.scss` instead of manual values for size and weight. If a value is missing add it to the variables instead.

2023-03-27 11:11 UTC, frjo commented on hypha/static_src/src/sass/apply/components/_docs-block.scss
> +        font-weight: 700;
See above about using variables.

2023-03-27 11:11 UTC, frjo commented on hypha/static_src/src/sass/apply/components/_data-block.scss
> +        padding: .5em 20px;
`rem` is preferred since it is related to the base font size.

2023-03-27 11:11 UTC, frjo commented on hypha/static_src/src/sass/apply/components/_button.scss
> +            padding: .5em 20px;
`rem` is preferred since it is related to the base font size.

2023-03-28 08:29 UTC, merged