Display average of score field for all reviews
HyphaApp/hypha pull request #3305
Opened 2023-03-28 20:27 UTC by gmurtaza00

Adds scores and an average score to the review outcomes in submissions tables.

![image](https://user-images.githubusercontent.com/111306331/228357674-f03705f8-ffaa-49a4-973a-1064456a0ffe.png)

Open to suggestion on this one, when no review has been submitted. We can either remove Avg. score or add a placeholder for 0 average

![image](https://user-images.githubusercontent.com/111306331/228357823-1d3cf745-98b7-407c-8305-30d1a5c56697.png)

Closes #3304

2023-03-29 12:35 UTC, frjo requested changes
Looks good, just one very minor fix before I send this to testing.

2023-03-29 12:35 UTC, frjo commented on hypha/static_src/src/sass/apply/custom/_custom.scss
> +    font-weight: 400;
Please use variables for font weight as well.

2023-03-29 13:02 UTC, frjo approved these changes

2023-04-04 07:46 UTC, theskumar commented
Thoughts on moving this here, @frjo @gmurtaza00 

![Screenshot 2023-04-04 at 07 45 07@2x](https://user-images.githubusercontent.com/236356/229723576-d7c6efbd-84e9-453c-b9e4-b97384684d67.jpg)

2023-04-04 16:40 UTC, gmurtaza00 commented
> Thoughts on moving this here, @frjo @gmurtaza00
> 
> ![Screenshot 2023-04-04 at 07 45 07@2x](https://user-images.githubusercontent.com/236356/229723576-d7c6efbd-84e9-453c-b9e4-b97384684d67.jpg)

![image](https://user-images.githubusercontent.com/111306331/229859370-acca7a55-4036-4132-9b6c-860fe7a3d55b.png)
![image](https://user-images.githubusercontent.com/111306331/229859442-71d8d285-c5ec-48bc-969e-b32119fcd508.png)

Does this seem alright?

2023-04-04 18:53 UTC, theskumar commented
That what's I was thinking, the red color was more of an indicator from my annotation tool. You can keep the font color same as the body font (black) and rest looks good to me.

2023-04-06 07:24 UTC, frjo requested changes
Move the css from custom file and we are good I think.

2023-04-06 07:24 UTC, frjo commented on hypha/static_src/src/sass/apply/custom/_custom.scss
> +}
`_custom.scss` should be empty in stock hypha. It is used to add your custom css without worrying about merge conflicts.

2023-04-06 07:24 UTC, frjo commented on hypha/static_src/src/sass/apply/components/_list.scss
> -
Good, this is some old left over css. Thanks for noticing it.

2023-04-10 09:05 UTC, frjo approved these changes

2023-04-27 17:46 UTC, gmurtaza00 commented
Initially NA score was being display as 99 and average was calculated using this score. Rebasing resolved this issue. Now score is displayed correctly and average is also being calculated correctly.

![image](https://user-images.githubusercontent.com/111306331/234944311-8ded5792-d502-47d5-b134-e3ba8ab73ad4.png)

2023-04-28 06:22 UTC, frjo approved these changes

2023-12-14 13:39 UTC, frjo commented
Closing this since this view is being replaced.

2023-12-14 13:39 UTC, closed without merging