#3410: Add link for dashboard/log in after application submission
HyphaApp/hypha pull request #3411
Opened 2023-05-15 20:15 UTC by gmurtaza00

After submitting application user, if the user is authenticated they will be presented with a link to go to back to dashbaord.

![image](https://github.com/HyphaApp/hypha/assets/111306331/a441f4a2-3f3a-44b8-9ee7-b0d124cc467b)

If user is not authenticated, they will be presented with a link to go to login page.

![image](https://github.com/HyphaApp/hypha/assets/111306331/bfdc27ff-a497-4a5f-a970-0a950bfad314)

Closes #3410

2023-05-16 05:12 UTC, theskumar requested changes
As there are not other primary actions on that page, I would suggest keep the paragraph, remove the link from it and then have a button `Goto Dashboard` and `Login` as two primary button at the bottom.

2023-05-16 05:12 UTC, theskumar commented on hypha/apply/funds/templates/funds/application_base_landing.html
> +			<a href="/dashboard/">{% blocktrans %}Return to my dashboard.{% endblocktrans %}</a>
Use `{% url "..."` here?

2023-05-16 05:12 UTC, theskumar commented on hypha/apply/funds/templates/funds/application_base_landing.html
> +			{% blocktrans %}Once you've activated an account, you can track your submissions after {% endblocktrans %}<a href="/login/">{% blocktrans %}logging in{% endblocktrans %}</a>.
Please use `url` tag here

2023-05-16 07:10 UTC, frjo commented
Nice feature! After implementing the url tag instead of hardcoding the paths I will put this on test.

2023-05-16 15:18 UTC, frjo approved these changes

2023-05-31 11:31 UTC, sandeepsajan0 commented on hypha/apply/funds/templates/funds/application_base_landing.html
> +			<a href="{% url 'dashboard:dashboard' %}"><button class="button button--primary">{% blocktrans %}Return to my dashboard.{% endblocktrans %}</button></a>
Looks good. Can we just use 'Go to' instead of 'Return' because return is a kind of reference to the previous location?

2023-06-12 09:45 UTC, merged