Use <relative-time> element to display time
HyphaApp/hypha pull request #3412
Opened 2023-05-16 08:26 UTC by theskumar

This use https://github.com/github/relative-time-element to make the
display of the datetime accessible, localized, concise and standard
across the site.

This also make use of the custom elements, which is also used by
wagtail 4 at different places in the CMS

2023-05-16 12:34 UTC, frjo requested changes
Solid improvement, just a small issue regarding version number in file name.

2023-05-16 12:34 UTC, frjo commented on hypha/templates/base-apply.html
> +        <script type="module" src="{% static 'js/esm/github-relative-time-element-4-3-0.js' %}"></script>
Can we remove the version number from the file name? A bit cumbersome on updates otherwise.

2023-05-16 12:51 UTC, theskumar commented on hypha/templates/base-apply.html
> +        <script type="module" src="{% static 'js/esm/github-relative-time-element-4-3-0.js' %}"></script>
Done.

2023-05-16 14:00 UTC, frjo requested changes

2023-05-16 14:00 UTC, frjo commented on package.json
>              [
Need to add `@github/relative-time-element` to `devDependencies`.

2023-05-16 14:00 UTC, frjo commented on package.json
>              [
If we select to use npm install and copy-npm-scripts instead of download-esm.

2023-05-17 06:34 UTC, theskumar commented on package.json
>              [
Take a look at this post for why we can't use npm for it (yet!), also why simply downloading packages from the cdn will also not work for esm modules. 

https://simonwillison.net/2023/May/2/download-esm/

2023-05-17 06:36 UTC, theskumar commented on package.json
>              [
I can add more info if you like to the `download-esm-modules` target to explain why and when to use it. Let me know. 

It's currently supposed to be used manually and rename the files (to remove the version) or if we keep the version number in the html, then update the version number in the html.

2023-05-17 10:13 UTC, frjo commented on package.json
>              [
Good arguments for `download-esm`. Can we have the make command rename the file? Printing out a messages about the need of renaming would work as well.

Renaming it manually is not a big thing, but may confuse a new developer, or us in a few month time :-).

2023-05-18 07:19 UTC, theskumar commented on package.json
>              [
Added some notes in Makefile and base_apply.html on how to work this setup.

2023-07-25 08:36 UTC, theskumar commented
This PR content is already merged to `main` so closing this now.

2023-07-25 08:36 UTC, closed without merging