#3417: Configured default visibility for review
HyphaApp/hypha pull request #3418
Opened 2023-05-18 16:44 UTC by gmurtaza00

Configured setting for default visibility of review. It can be set as **private** or **reviewers**. 

- Private: Visible only to staff.
- Reviewers: Visible to other reviewers and staff.

**Setting to consider:**

- ```DEFAULT_REVIEW_VISIBILITY```

Closes #3417

2023-05-19 08:12 UTC, frjo requested changes
Looks good, just rename the setting and move it up a bit in base.py.

2023-05-19 08:12 UTC, frjo commented on hypha/settings/base.py
> +DEFAULT_REVIEW_VISIBILITY = env.str('DEFAULT_REVIEW_VISIBILITY', 'private')
Please rename to `REVIEW_VISIBILITY_DEFAULT` and move it up to the `# Hypha custom settings` section.

2023-05-19 18:12 UTC, frjo approved these changes

2023-05-31 10:55 UTC, sandeepsajan0 approved these changes

2023-12-14 13:53 UTC, frjo commented
@theskumar Any issues with this one?

2023-12-15 05:38 UTC, theskumar commented
Looks good to me.

2023-12-18 07:46 UTC, merged