Add proposal form field to concept determination
HyphaApp/hypha pull request #3425
Opened 2023-05-29 12:04 UTC by sandeepsajan0

Fixes #3049 

1. Add a disabled proposal form field to concept determination.
2. It gets enabled only if the user selects 'Approved' in the determination field.
3. If it is enabled, it is required, else optional.

Update Status is working in the same way as it was working. We have only changed the behavior for the concept's Add Determination.

2023-05-29 13:04 UTC, frjo requested changes
Some minor JS comments.

Alos added code that set the initial outcome value based on the action taken. This works for the old static determinations forms but not for the new streamfield ones.

Please see if my implementation is ok.

2023-05-29 13:04 UTC, frjo commented on hypha/static_src/src/javascript/apply/determination-template.js
> +            var proposal_form = document.querySelector('#id_proposal_form');
`const` instead of `var`.

2023-05-29 13:04 UTC, frjo commented on hypha/static_src/src/javascript/apply/determination-template.js
>          }
I think the only jQuery is at the end, the `$(DeterminationCopy.selector()).each((index, el)` part.

If you have time, can you convert that to plain JS and remove all jQuery references from this file.

2023-05-30 07:32 UTC, frjo approved these changes

2023-06-08 11:22 UTC, merged

2024-09-25 15:52 UTC, bickelj commented on hypha/static_src/src/javascript/apply/determination-template.js
> +            const proposal_form = document.querySelector('#id_proposal_form');
I checked out 3a0b2c290f0aaaeda9ae6f7b7b2cb290a90ba004 and tried `grep -ir id_proposal_form *` hoping to find the template or code that creates an element with `id=id_proposal_form` but I don't see it. Am I missing something or is a change to the template missing? I get the following error on the branch associated with #4142:
```
Uncaught TypeError: proposal_form_field is null
    <anonymous> https://hypha.test/static/js/determination-template.js:53
    EventListener.handleEvent* https://hypha.test/static/js/determination-template.js:51
    <anonymous> https://hypha.test/static/js/determination-template.js:57
```