Show who can see archived submissions
HyphaApp/hypha pull request #3646
Opened 2023-11-06 19:06 UTC by wes-otf

Fixes #3388.

This PR adds an indication as to what user roles can see an archived submission based off of [existing settings](https://github.com/HyphaApp/hypha/issues/3388#issuecomment-1793773642). 

## Screenshots

_With default Hypha settings_
<img width="1419" alt="Screenshot 2023-11-06 at 12 04 13 PM" src="https://github.com/HyphaApp/hypha/assets/145372368/96d323c9-194d-4e95-9c43-a2ccf0b9dd67">

_After updating settings to allow Staff and Staff Admin to see archives_
<img width="1419" alt="Screenshot 2023-11-06 at 12 05 02 PM" src="https://github.com/HyphaApp/hypha/assets/145372368/5cc0d6b5-22fa-4242-bf7c-5105f63081e6">

_After updating settings to only allow Staff Admin (not Staff) to see archives_
<img width="1419" alt="Screenshot 2023-11-06 at 12 03 09 PM" src="https://github.com/HyphaApp/hypha/assets/145372368/df9f6806-b75c-473c-87f2-b587630f8a9b">

2023-11-07 05:09 UTC, theskumar requested changes
Add notes to make the code more modular and readable.

2023-11-07 05:09 UTC, theskumar commented on hypha/apply/funds/views.py
> +            archive_string=archive_string,
This is what I would do make the code more separated by concern. 

1. Create a template tag `join_with_commas`that joins and displays a list of items and separated by a `,` and `and` the code below. It will be useful other places
2. Make a function `get_archived_submission_visibility_groups()`, either in `appy.funds.utils` or `apply.funds.permissions` module
3. The early return with `self.object().is_archive` is not needed, it can be replaced with final return like this

```python 
return super().get_context_data(
    archived_submission_visibility_groups=get_archived_submission_visibility_groups()
    ...
```



```python
def join_with_commas(obj_list):
    """Takes a list of objects and returns their string representations,
    separated by commas and with 'and' between the penultimate and final items
    For example, for a list of fruit objects:
    [<Fruit: apples>, <Fruit: oranges>, <Fruit: pears>] -> 'apples, oranges and pears'
    
    Inspired by: https://stackoverflow.com/a/1242107
    """
    if not obj_list:
        return ""
    l=len(obj_list)
    if l==1:
        return f"{obj_list[0]}"

    return f"{', '.join(str(obj) for obj in obj_list[:l-1])} and {obj_list[l-1]}"
```

2023-11-07 05:09 UTC, theskumar commented on hypha/apply/funds/templates/funds/applicationsubmission_detail.html
> +            {{ archive_string }}
Based on the suggested refractor, this code code will look more like. 

```
{% trans "This submission has been archived. This is visible to the roles" %} {{ archived_submission_visibility_groups|join_with_comma }}
```

2023-11-07 07:44 UTC, frjo commented
The po and pot files I tend to update in separate PRs for practical reasons.

If you update po and pot files in more than one PR you tend to get merge conflicts. No problem keeping them here, good to get them updated.

2023-11-07 18:48 UTC, wes-otf commented
@theskumar this is great feedback, thanks a ton! 

I was originally working to make it more sentence-like (ie. "role, role and role") but wondered how that would impact translations if different linguistics were to come into play. If that might be an issue I can refactor my last commit. Definitely makes sense to have it more modular though.

2023-11-07 18:50 UTC, wes-otf commented
@frjo Noted with the translation files - would it make more sense to revert them to what's on main and follow up with the altered files? I have translations committed to #3636 that I can revert too and then do all of them at once after it's all merged.

2023-11-13 17:28 UTC, wes-otf commented
Reverting this back to a draft as I add features from #3389.

2023-11-14 19:42 UTC, wes-otf commented
@frjo @theskumar I believe this is ready to go. The only piece that is still up for discussion would be the behavior of the `403 Forbidden` page when a user without archive access tries to view and archived submission. The options I see are:

- Redirect the user to the submission dashboard
- Create a new "Access Denied" page/view that would allow all instances of `raise PermissionDenied` to be a little more descriptive and clean
- Leave the existing functionality as is

Let me know your thoughts!

2023-11-23 06:39 UTC, frjo approved these changes

2023-11-23 07:08 UTC, theskumar commented
> @frjo @theskumar I believe this is ready to go. The only piece that is still up for discussion would be the behavior of the `403 Forbidden` page when a user without archive access tries to view and archived submission. The options I see are:
> 
> * Redirect the user to the submission dashboard
> * Create a new "Access Denied" page/view that would allow all instances of `raise PermissionDenied` to be a little more descriptive and clean
> * Leave the existing functionality as is
> 
> Let me know your thoughts!

Explicit is better than implicit. I would suggest going with -- `Create a new "Access Denied" page/view that would allow all instances of raise PermissionDenied to be a little more descriptive and clean.`

2023-11-28 14:37 UTC, wes-otf commented
@theskumar All sounds good! The functionality for the 403 page is pretty much mirrored from the 404. It can be customized in Wagtail admin and is triggered when any `django.core.exceptions.PermissionDenied` error is raised. By default, it looks like the following:

![Screenshot 2023-11-28 at 8 55 34 AM](https://github.com/HyphaApp/hypha/assets/145372368/b2fd8cfe-5dd3-4bed-be1c-78b2066500e7)
-------
With the Wagtail admin prompts:
![Screenshot 2023-11-28 at 9 02 15 AM](https://github.com/HyphaApp/hypha/assets/145372368/c39fdda2-2928-4878-81ef-95ad2b5fc4f0)

2023-11-28 14:39 UTC, wes-otf commented
This was also tested in the archive context (user with staff role attempted to view an archived submission) and worked well.

2023-12-01 21:02 UTC, wes-otf commented
This was tested by @Techslammer & all worked as intended. The latest changes of the 403 page hadn't been deployed to test but that was a minor change that shouldn't change too much. Can retest with that if you'd prefer @frjo, otherwise I'll mark it as ready.

Have a nice weekend y'all!

2023-12-01 22:01 UTC, merged