maintainance/svg updates
HyphaApp/hypha pull request #3711
Opened 2024-01-07 19:01 UTC by theskumar

- Upgrade heroicons to 2.6.0, adds support for heroicons_mirco
- Remove/upgrade sprite icons
- Update icons in the global messages widget
- Remove unused bgg-logo sprite
- Update calendar icon with heroicon
- fixup! Remove/upgrade sprite icons
- Update anchor-link icon
- Remove speech-bubble icon and link—-open-feed, link--close-feed and link—to-top
- Remove arrow-up and arrow-down
- Remove arrow-split
- Remove "website" icon
- Remove “error” icon
- Update like & dislike button in the screening section
- fixup! Remove/upgrade sprite icons

2024-01-08 08:35 UTC, frjo approved these changes
Will be nice to have one single source for all icons. They will all have the same look and there is no guessing where they come from.

If we in the future want to change icon set it will be easier as well.

2024-01-09 12:49 UTC, theskumar commented
> Will be nice to have one single source for all icons. They will all have the same look and there is no guessing where they come from.

I didn't fully understand this. Did you intend to say not use heroicons? As for the guess work, I believe heroicons template tags avoids the guess work, and is very explicit where the icons came from. They are also quite isolated for each use, and can be easily updated with find and replace. 

For the custom icons, I was thinking to use web components and be included with a template tag. Thoughts?

2024-01-11 09:24 UTC, frjo commented
I ment that the heroicons is a good single source for all icons.

2024-01-17 06:16 UTC, theskumar commented
Rebased on top of #3722 to avoid merge conflicts.

2024-01-30 06:32 UTC, frjo commented
I have merged in all "Remove public…" PRs before this one now so this can be rebased of main.

2024-01-30 06:39 UTC, theskumar commented
Awesome, will do it now.

2024-01-30 07:16 UTC, frjo requested changes
One minor issue.

2024-01-30 07:16 UTC, frjo commented on hypha/apply/home/templates/apply_home/includes/apply_listing.html
> -{% load i18n bleach_tags markdown_tags wagtailcore_tags %}
I think ´ markdown_tags´  are needed. I added `{{ page.description|markdown|bleach }}`.

2024-01-30 07:17 UTC, theskumar commented on hypha/apply/home/templates/apply_home/includes/apply_listing.html
> -{% load i18n bleach_tags markdown_tags wagtailcore_tags %}
I agree.

2024-01-30 07:19 UTC, theskumar commented on hypha/apply/home/templates/apply_home/includes/apply_listing.html
> +{% load i18n bleach_tags wagtailcore_tags heroicons %}
```suggestion
{% load i18n bleach_tags wagtailcore_tags markdown_tags heroicons %}
```

2024-01-30 07:26 UTC, frjo requested changes

2024-01-30 07:26 UTC, frjo commented on hypha/public/utils/models.py
Looks like we need this file for a bit longer.

2024-01-30 07:47 UTC, theskumar commented on hypha/public/utils/models.py
Added back, got removed while rebasing

2024-01-30 08:08 UTC, frjo approved these changes

2024-01-30 08:08 UTC, merged