WIP: Add server side previews to the application workflow
HyphaApp/hypha pull request #3725
Opened 2024-01-12 23:43 UTC by wes-otf

Closes #3545.

This creates the option to require a user to preview their form before submitting it. The requirement is set on a per fund/lab basis, and is a required checkbox when the lab/fund is configured in Wagtail admin. The preview first saves the application as a draft, then presents the user with a preview of their application. Upon viewing, the user can either edit or submit as seen in the flow diagram below.

*Sloppy Flow Diagram:*
![Preview_Flow](https://github.com/HyphaApp/hypha/assets/145372368/7889e50f-8918-4aa7-9e96-37e590f7ce6f)

*Screenshots*:
<img width="239" alt="Screenshot 2024-01-12 at 18 42 15" src="https://github.com/HyphaApp/hypha/assets/145372368/d9801fa8-ebf5-41b9-925f-5ba16bc208b7">
<img width="1136" alt="Screenshot 2024-01-12 at 18 42 37" src="https://github.com/HyphaApp/hypha/assets/145372368/c2e56625-71cf-41d0-83ba-121187b535e4">

PR is a WIP as I'd like to polish this a bit more, add unit tests & more detailed comments.

2024-01-13 18:23 UTC, theskumar commented
Do we really need a configuration option. I would suggest keeping it  as default for all the rounds/labs. 

One less configuration to care about.

2024-01-14 11:20 UTC, frjo commented
This look like a nice implementation!

I would also prefer no option to make it more simple.

We can ask the other implementors and if some have really strong opinopn on it we might add a global env var to turn the previews off.

I can not see an organisation that wants previews for some fund/lab but not all.

2024-01-16 16:42 UTC, wes-otf commented
Thanks @frjo @theskumar, this was great feedback! After chatting today in the maintainers meeting it seems like the path forward is global configurations for the previews rather than per-fund/lab as OTS brought up that some organizations might not want this feature. Will have those changes up soon!

2024-01-19 08:52 UTC, frjo requested changes
This works really well in my testing. One small comment around the new env setting.

There is also an issue for sites that set:

```
FORCE_LOGIN_FOR_APPLICATION = False
```

The applicant fill in the submission form as anonymous (not logged in) and click "Preview and submit". They then have the option to click "Submit for review" or "Edit". Both will take them to the login screen without any explanations.

An account is created for them and the e-mail is sent out but we do not communicate this fact to them in Hypha.

If you set:

```
REQUIRE_PREVIEW = False
```

You still have the same issue if the applicant click the optional "Preview" button.

How should we handle this?

A simple way would be to make preview only work for logged in users.

2024-01-19 08:52 UTC, frjo commented on hypha/settings/base.py
> +REQUIRE_PREVIEW = env.bool("REQUIRE_PREVIEW", True)
1. Can we move this up to the "# Hypha custom settings" section. Good to have all the custom stuff in one place I think.
2. The setting name is a bit terse, could we do something like `SUBMISSION_PREVIEW_REQUIRED`? Something that tell what part of Hypha the setting refers to.

2024-01-19 13:59 UTC, wes-otf commented
@frjo thanks for testing! This is definitely an oversight from me, I'll go back to the drawing board for this one. 

> A simple way would be to make preview only work for logged in users.

I think this would also negate `FORCE_LOGIN_FOR_APPLICATION = False` if previewing was a piece of the submission process right? If you clicked "Preview and submit" and were forced to login to preview

2024-01-19 14:10 UTC, frjo commented
@wes-otf I think the best solution is to only activate previewing for logged in users (regardless if `REQUIRE_PREVIEW` is set to true or false).

We then document that `FORCE_LOGIN_FOR_APPLICATION = False` will disable previewing of submissions for non logged in users.

What do you think?

2024-01-19 15:32 UTC, wes-otf commented
@frjo Yeah I think that is the only answer that really makes sense. All the options I can think of would either be a major overhaul or a potential security vulnerability

2024-01-19 23:44 UTC, wes-otf commented
This should be all set now!

2024-01-24 15:14 UTC, frjo approved these changes

2024-01-24 18:14 UTC, wes-otf commented
@frjo I just created two labels for user testing vs dev testing. Let me know if you think that makes sense moving forward

2024-01-29 19:55 UTC, merged