Update primary nagivation dropdown UX
HyphaApp/hypha pull request #3769
Opened 2024-02-12 11:13 UTC by theskumar

## Description

- Fix the dropdown being hidden on the beta all page
- Use mouseover for quick access
- Update over states
- Update the urls to that any external urls can also be added via
  settings, removes dependeny of `reverse` while specifying urls
- How active page in the dropdown as well, a dark-blue border
- Update the focus outline to be a simple dashed-border, instead of bulky outline

## Test Steps

 - [ ] Checkout the primary navigation in the top-header

2024-02-12 12:25 UTC, frjo commented
Nice works! Open on hover, or not, is a personal preference. I will ask the other maintainer in the meeting tomorrow what they prefer.

Two minor items that would be nice to resolve:

1. The dotted outline looks a bit off I think. I see it uses `focus-visible` so it should only show for keyboard navigation. But I still see it using only the mouse/trackpad.
2. When you hover over the longes menu item the bold text makes the with of the menu increase a tiny bit. 

<img width="602" alt="Skärmavbild 2024-02-12 kl  13 07 59" src="https://github.com/HyphaApp/hypha/assets/191392/14b7eb3a-d5aa-47be-a156-7be773686593">

2024-02-12 12:25 UTC, frjo requested changes

2024-02-12 12:25 UTC, frjo commented on hypha/core/templates/core/navigation/primarynav-apply.html
> +                        <a class="nav__link {% if target_url in request.path %}nav__link--active{% endif %}" href="{{ item.url }}" role="menuitem">
`target_url` should be replace with `item.url` here as well I think.

2024-02-12 12:25 UTC, frjo commented on hypha/core/templates/core/navigation/primarynav-apply.html
> +                                class="min-w-48 absolute block bg-white shadow-xl z-20 mt-4 border rounded-sm"
`min-w-48` seems to not generate any styles? Why not use `min-w-max`? Having menu item break on two lines is undesirable.

2024-02-12 12:31 UTC, theskumar commented on hypha/core/templates/core/navigation/primarynav-apply.html
> +                                class="min-w-48 absolute block bg-white shadow-xl z-20 mt-4 border rounded-sm"
`min-w-48` ensure the width of two dropdown are similar. It won't break them in two lines as it's not setting any max width. That said, I should consider added generous max-width so the dropdown doesn't look weird for a link with too many words. 

Let me know if it all sounds reasonable?

2024-02-12 12:31 UTC, theskumar commented on hypha/core/templates/core/navigation/primarynav-apply.html
> +                        <a class="nav__link {% if target_url in request.path %}nav__link--active{% endif %}" href="{{ item.url }}" role="menuitem">
🖖🏼

2024-02-12 12:34 UTC, theskumar commented
> Nice works! Open on hover, or not, is a personal preference. I will ask the other maintainer in the meeting tomorrow what they prefer.
> 
> Two minor items that would be nice to resolve:
> 
> 1. The dotted outline looks a bit off I think. I see it uses `focus-visible` so it should only show for keyboard navigation. But I still see it using only the mouse/trackpad.
> 2. When you hover over the longes menu item the bold text makes the with of the menu increase a tiny bit.
> 
> <img alt="Skärmavbild 2024-02-12 kl 13 07 59" width="602" src="https://private-user-images.githubusercontent.com/191392/304062662-14b7eb3a-d5aa-47be-a156-7be773686593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDE1MTgsIm5iZiI6MTcwNzc0MTIxOCwicGF0aCI6Ii8xOTEzOTIvMzA0MDYyNjYyLTE0YjdlYjNhLWQ1YWEtNDdiZS1hMTU2LTdiZTc3MzY4NjU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMjMzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDBjYzc4YjhkNDU2NDkxMDM1NjQzN2QxY2Y5ZjQ3NmVjZTIwZDE0NWVmYmIyMjA0YjUyOWZiYTY3MTQ5MmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qd_2-PI8WcPbPzq-Hbc4ZHsPTKztYLNrIYyjn3DCyWA">

Which browser are you using, this is what i see: 

![Screenshot 2024-02-12 at 12  33 18@2x](https://github.com/HyphaApp/hypha/assets/236356/efd8c3ed-c7d5-43c1-a421-a5335b25d321)

2024-02-12 12:35 UTC, theskumar commented
The visible-focus seems to be not working with `x-trap` and mouseover, already spent sometime trying to figure out a solution, but no luck. I'll give it another try.

2024-02-12 12:37 UTC, theskumar commented on hypha/core/templates/core/navigation/primarynav-apply.html
> +                                class="min-w-48 absolute block bg-white shadow-xl z-20 mt-4 border rounded-sm"
This is could be b/w you are not using the latest tailwind, which introduced `min-w-*`

2024-02-15 08:41 UTC, theskumar commented
@frjo any feedback on the nav getting opened while on hover? The outline issue is only happening if the mousehover is used. If mouseover is not desired, there is need to chase after the focus issue.

2024-02-15 10:02 UTC, theskumar commented
Update and fixed the outline issue on safari, it should look better now. 

![Screenshot 2024-02-15 at 10  01 57@2x](https://github.com/HyphaApp/hypha/assets/236356/0d9c6591-cccd-4ab0-97aa-ca8183c2564e)

2024-02-16 09:20 UTC, frjo approved these changes

2024-02-16 09:20 UTC, frjo commented
Latest version on test now.

2024-02-16 21:26 UTC, wes-otf commented
Hey! Added functionality looks good to me, I'm just a little confused about what purpose the dotted border serves? I didn't see it changing on test at all, just stayed on `All Submissions`/`All Projects`. On Firefox 121 I can't seem to use keyboard nav at all with Hypha if that's what this is in reference to?

2024-02-22 10:22 UTC, merged