Fix error message alignment for change password form
HyphaApp/hypha pull request #3868
Opened 2024-04-10 17:58 UTC by theskumar

Inline error messages

![Screenshot 2024-04-10 at 5  58 42@2x](https://github.com/HyphaApp/hypha/assets/236356/44710100-99f6-419e-b8a0-2c438f06f301)

Fixes https://github.com/HyphaApp/hypha/issues/3842

## Test Steps

 - [ ] Try changing the password and use different password while retyping

2024-04-11 06:35 UTC, frjo commented
Can we have the error message pop up on the "New password" field instead of the "New password confirmation" field?

2024-04-11 06:37 UTC, frjo requested changes

2024-04-11 06:37 UTC, frjo commented on hypha/apply/templates/forms/includes/field.html
> +                    <h6 class="form__error-text">
Can we get rid of the "h6" as well. The original Hypha theme misuse headings quite a lot.

2024-04-13 05:20 UTC, theskumar commented on hypha/apply/templates/forms/includes/field.html
> +                    <h6 class="form__error-text">
Sure

2024-04-13 05:20 UTC, theskumar commented
> Can we have the error message pop up on the "New password" field instead of the "New password confirmation" field?

let me take a stab at it. I believe it's the Django's default password change form.

2024-04-13 17:56 UTC, theskumar commented on hypha/apply/templates/forms/includes/field.html
> +                    <h6 class="form__error-text">
Updated.

2024-04-13 18:03 UTC, theskumar commented
> Can we have the error message pop up on the "New password" field instead of the "New password confirmation" field?

I cross checked and the validation logic comes from the default ChangePassword View/Form from Django. So I would try avoid changing the position of the error message unless you have a strong opinion/need for it. Also, in the latest version of Django the code related to validation of passwords has been updated, so I would advice we don't implement a custom validate logic which will then need to be maintained. 

Thinking out loud, the validation error messages in the screenshot is shown only after both the passwords match, so I think it might be too confusing to users.

2024-04-17 13:23 UTC, wes-otf approved these changes

2024-04-17 13:58 UTC, frjo approved these changes

2024-04-17 13:58 UTC, merged