Utilize emails as display name on comments when no name is set
HyphaApp/hypha pull request #3896
Opened 2024-04-22 09:24 UTC by wes-otf

Fixes #3895. Quick one I noticed while working on the partner comment stuff. Comments will now display with the user email where no full name is set.

## Screenshots
<img width="1303" alt="Screenshot 2024-04-22 at 05 20 24" src="https://github.com/HyphaApp/hypha/assets/145372368/e9bc89c0-b27a-44bb-98ca-28401875dd49">

## Test Steps

 - [ ] Clear the `Full Name` field on https://test-apply.hypha.app/account/ and select `Update Profile`
 - [ ] Navigate to a submission that has comments from the current user account
 - [ ] Ensure that the current email appears on the comments instead of an empty name

2024-04-22 09:30 UTC, wes-otf commented
branched from my other PR on accident, should be all set now.

2024-04-22 09:33 UTC, frjo approved these changes
Nice fix.

2024-04-30 04:42 UTC, theskumar commented
Is there any privacy concern with emails being display. Is so we can try showing only first few characters and the domain. 

e.g. for `saurabh@example.com` -> `sau...@example.com`

2024-04-30 15:15 UTC, wes-otf commented
Hey! In OTF's usage I don't see a scenario where there could be a concern of privacy. Most of the time the email address is accessable via the application overview anyway as far as I know. Let me know if there's a scenario you think this could be an issue though

2024-05-01 07:23 UTC, theskumar commented
> Hey! In OTF's usage I don't see a scenario where there could be a concern of privacy. Most of the time the email address is accessable via the application overview anyway as far as I know. Let me know if there's a scenario you think this could be an issue though

I think i was primarily thinking around the emails of reviewers (internal and external). But then i as also thinking stricter and more privacy friendly implementation without a use-case.

I used something like this for the long filenames, where the use-case was more of UX but here it might act as good UX (for long emails) & privacy by default feature.

just to be sure, I don't have a strong argument/opinion for this. We go with what you decide, I'm just get worried when PII get exposed to a wider audience. 

https://github.com/HyphaApp/hypha/blob/d647118ee827eb1c30ff50620ac221a78726591c/hypha/apply/utils/templatetags/apply_tags.py#L30-L40

2024-05-01 19:59 UTC, wes-otf commented
ahh I see, that totally makes sense! I'm absolutely all for preserving privacy wherever possible. 

I chatted with staff a bit today and I guess per their bylaws OTF's external reviewers shouldn't even be able to interact with the applicants (more in #3907). If we move forward and make it so only staff can see comments from external reviewers, then only internal reviewers are to be considered, which would [always be staff](https://github.com/HyphaApp/hypha/blob/fb3356810d27fa64334acab161eae381540c112c/hypha/apply/funds/forms.py#L446) and thus appear as the [Org's long name](https://github.com/HyphaApp/hypha/blob/fb3356810d27fa64334acab161eae381540c112c/hypha/apply/activity/templatetags/activity_tags.py#L30-L35) in comments rather than any other display name. I'll ask around and see what folks think though, especially if there's a need for partners' identities to be concealed or anything.

2024-05-03 11:41 UTC, frjo commented
Works well in my testing.

2024-05-07 18:58 UTC, wes-otf commented
Chatted with staff & Slammer around this - currently the only time someone who isn't staff would be seeing a user's email would be in the case of a partner and in OTF's use case that's fine, the partner & applicant are expected to have this info already. I think this might be worth a revisit down the road though as we continue to expand and rethink the comment section.

2024-05-07 18:59 UTC, wes-otf commented
For now I think this is ready to go though unless there's any objections

2024-05-08 04:49 UTC, theskumar commented
When a new comment is posted, the applicant get this email. `hypha/apply/activity/templates/messages/email/comment.html`. If the name of the commenter is not set, the email contains the email of the commenter. Should that be fixed? Maybe use more generic phrase. like `comment by Staff` instead or `comment by xyz@email.com`

2024-05-08 06:44 UTC, frjo commented
@theskumar Good point!

How do you all feel about this suggestion?

We let the short name be just the first part of the e-mail address.

```
    def get_short_name(self):
        return self.email.split("@")[0]

```

We then replace most uses of "full_name" with "display_name" throughout Hypha.

If the user has not set a name we have something to display, but we do not leak the full e-mail address unnecessarily.

2024-05-08 06:46 UTC, frjo requested changes

2024-05-08 06:46 UTC, frjo commented on hypha/apply/users/models.py
>          is_contracting = f" ({CONTRACTING_GROUP_NAME})" if self.is_contracting else ""
We should likely add "Partner" here.

2024-05-08 06:46 UTC, frjo commented on hypha/apply/users/models.py
> +        return f"{display_name.strip()}{is_apply_staff}{is_reviewer}{is_applicant}{is_finance}{is_contracting}"
I think we can remove "strip()" from this line. It is already done in "get_full_name".

2024-05-08 18:20 UTC, wes-otf commented
All great catches! The short name seems to be nice will even tighten up the options in the top right now that it doesn't need to include an email domain:
<br>
*before*
<img width="389" alt="Screenshot 2024-05-08 at 14 15 52" src="https://github.com/HyphaApp/hypha/assets/145372368/14886381-5b86-40d1-9125-7c1fd7299a7a">

*after*
<img width="389" alt="Screenshot 2024-05-08 at 14 16 16" src="https://github.com/HyphaApp/hypha/assets/145372368/d82ce373-9d94-4636-923f-5b092c90949e">

other changes should also be more in-line with what was mentioned here

2024-05-08 18:23 UTC, wes-otf commented on hypha/apply/users/models.py
> +        display_name = str(self)
figured this was better than duplicating the str dunder logic

2024-05-08 18:29 UTC, frjo commented on hypha/apply/users/models.py
> +        is_partner = f" ({PARTNER_GROUP_NAME})" if self.is_applicant else ""
Should be `self.is_partner`

2024-05-08 21:51 UTC, frjo approved these changes

2024-05-29 12:36 UTC, sandeepsajan0 approved these changes

2024-06-01 08:28 UTC, merged