Add application submission id everywhere, with an optional prefix
HyphaApp/hypha pull request #3930
Opened 2024-05-20 03:38 UTC by theskumar

This PR allow adding an option prefix to the submission ID's that are auto generated. 

The prefix can be added by going to round or lab settings page. 

This PR also ensure the prefix or application ID displayed along with title almost everywhere for each reference. Since the title of application is not unique, this helps add uniqueness to it. 

The autolinking of submission ids in communication has be updated to account for application id prefix

Fixes https://github.com/HyphaApp/hypha/issues/3830

![Screenshot 2024-05-20 at 3  38 36@2x](https://github.com/HyphaApp/hypha/assets/236356/0360dbc8-291d-486d-9927-657b20f71831)

![Screenshot 2024-05-20 at 4  43 55@2x](https://github.com/HyphaApp/hypha/assets/236356/8b10a760-097b-44f1-bba6-0033b04b962c)

![Screenshot 2024-05-20 at 4  44 32@2x](https://github.com/HyphaApp/hypha/assets/236356/2b81b695-f114-472f-b77d-87ca23571503)
![Screenshot 2024-05-20 at 4  45 05@2x](https://github.com/HyphaApp/hypha/assets/236356/3c3ab582-ae8c-4c03-8ae6-515c06582bb2)

## Test Steps

 - [ ] general checks across the site
 - [ ] check notification generate - slack, email, etc.

2024-05-20 10:29 UTC, sandeepsajan0 commented on hypha/apply/funds/models/submissions.py
> +    def title_with_id(self):
Can we use this method to provide 'title' or 'title with public_id' based on a feature flag? Some org might not want to show the application count or not at least to the applicant.

2024-05-20 13:34 UTC, theskumar commented on hypha/apply/funds/models/submissions.py
> +    def title_with_id(self):
Great suggestion, however, if possible I would try keep the number of feature flags to minimal, unless any adaptor thinks it's a deal break for them. 

@wes-otf @frjo If you happen to present this in adopter meeting, can we try get an idea if someone would want to hide this info? The ids have been and will always be available in the url.

2024-05-22 15:26 UTC, frjo requested changes
Do we support search for prefix or number (\#123)?

2024-05-22 15:26 UTC, frjo commented on hypha/apply/funds/templates/funds/includes/rendered_answers.html
> +        <div class="">
Remove the class attribute.

2024-05-22 15:26 UTC, frjo commented on hypha/apply/funds/models/submissions.py
> +    def title_with_id(self):
Did not sound like a need to hide exist. Could we provide a template for this? Making it easy to adopt the output.

You mentioned that some wanted to have the prefix first.

2024-05-27 10:56 UTC, theskumar commented on hypha/apply/funds/models/submissions.py
> +    def title_with_id(self):
Updated in https://github.com/HyphaApp/hypha/pull/3930/commits/0e406525490d9609c20cf2d0850f23314561adcb

2024-05-27 10:57 UTC, theskumar commented
Getting the submission prefix in the url as well is lot of work also requires decent testing. I think it would better to tackled in another pr.

2024-05-28 17:17 UTC, frjo commented
@theskumar I think this needs rebuild migrations and a rebase. Merged in a number of PRs today.

2024-05-29 13:56 UTC, theskumar commented
@frjo updated! :)

2024-05-29 15:22 UTC, frjo approved these changes

2024-06-14 21:26 UTC, wes-otf commented on hypha/apply/activity/adapters/slack.py
>              "A new {comment.visibility} comment has been posted on <{link}|{source.title}> by {user}"
Should this be:
```suggestion
            "A new {comment.visibility} comment has been posted on <{link}|{source.title_text_display}> by {user}"
```
That's only one I noticed that was missing on slack

2024-06-14 21:29 UTC, wes-otf commented
Super small issue from my testing with the slack comment notif but otherwise works great!

2024-06-15 06:19 UTC, merged