Add user menu draft for various versions
HyphaApp/hypha pull request #3943
Opened 2024-05-27 09:56 UTC by sandeepsajan0

Fixes #3888 

## Test Steps

 - [ ] …

2024-06-03 16:54 UTC, frjo requested changes

2024-06-03 16:54 UTC, frjo commented on hypha/templates/includes/login_button.html
> +            <button x-on:click="show = ! show" class="button--narrow font-bold text-center flex items-center justify-center px-2 hover:bg-black hover:text-white active:bg-black active:text-white focu
Add a "button" class here. The adds the small runded corners we have on all buttons now.

2024-06-03 16:54 UTC, frjo commented on hypha/templates/includes/login_button.html
> +            <button x-on:click="show = ! show" class="button--narrow font-bold text-center flex items-center justify-center px-2 hover:bg-black hover:text-white active:bg-black active:text-white focu
Add a "button" class here.

2024-06-03 16:54 UTC, frjo commented on hypha/templates/includes/login_button.html
> +            <div x-show="show" x-transition @click.outside="show = false" class="min-w-36 absolute block bg-white shadow-xl z-20 border-y rounded-sm end-0 top-10">
I think I prefer without "end-0" so the meny align with the left of the button. Personal and minor.

2024-06-12 18:52 UTC, wes-otf commented on hypha/templates/includes/login_button.html
> +                        {% trans "Wagtail admin" %}</a>
```suggestion
                        {% heroicon_mini "wrench-screwdriver" size=20 class="mr-1 inline align-text-bottom" %} {% trans "Admin" %}</a>
```

what are the thoughts on swapping this to be more inline with #3922?

2024-06-12 18:54 UTC, wes-otf commented
Worked well in testing! I think just a few stylistic changes and it should be ready to go. Nice addition!

2024-06-12 18:55 UTC, wes-otf commented on hypha/templates/includes/login_button.html
> +                        {% trans "Wagtail admin" %}</a>
I just copied the line from #3922, the tailwind may need some tweaking

2024-06-13 09:25 UTC, frjo commented on hypha/templates/includes/login_button.html
> +            <div x-show="show" x-transition @click.outside="show = false" class="min-w-36 absolute block bg-white shadow-xl z-20 border-y rounded-sm end-0 top-10">
Does not work with short names I found out.

2024-06-13 09:25 UTC, frjo approved these changes

2024-06-13 14:17 UTC, merged