Notification upon profile update
HyphaApp/hypha pull request #3970
Opened 2024-06-06 15:26 UTC by bickelj

Fixes #3969

## Test Steps

- Log in as any user
- Go to Account page `/account/`
- Change a field such as name
- Click save
- A notification box should say that the profile was updated

2024-06-07 07:09 UTC, frjo requested changes

2024-06-07 07:09 UTC, frjo commented on hypha/apply/users/views.py
> +    success_message = "Profile Updated."
Please make translatable.

2024-07-30 16:39 UTC, bickelj commented
@frjo Is there anything else we need to do on this one?

2024-07-31 07:39 UTC, frjo requested changes

2024-07-31 07:39 UTC, frjo commented on hypha/apply/users/views.py
> +    success_message = _("Profile Updated.")
Very minor but we avoid title case on Hypha. Make it "Profile updated." instead.

2024-08-09 08:39 UTC, frjo approved these changes

2024-08-09 08:40 UTC, merged