Enhancement/cookie popup improvements
HyphaApp/hypha pull request #3976
Opened 2024-06-06 21:02 UTC by wes-otf

Fixes #3925. **TLDR**:
 - Cookie consent preference is now stored in local storage rather than using cookies
 - Improves on the existing cookie banner by adding a `Learn More` option where users can read more about the essential & analytic cookies, and toggle analytics specifically. 
 - If analytics are not used, the user is no longer given the option to opt out, as Hypha only uses essential cookies by default. 
 - Added a link/button to the footer default that allows the user to re-open the cookie prompt without having to clear it from their local storage.

Drafting for now as it needs: mobile/small screen support, some accessibility additions & documentation of local storage vars/exposed functions (ie. `openConsentPrompt`)

## Demo

_with analytics cookies_

https://github.com/HyphaApp/hypha/assets/145372368/a06942f9-9e99-4113-8903-dc2695dd7787

_without analytics cookies (default)_

https://github.com/HyphaApp/hypha/assets/145372368/0ba27988-22ba-4267-8945-6dad4a125e1d

## Test Steps

 - [ ] …

2024-06-13 20:13 UTC, wes-otf commented
tomorrow will add a quick blurb to the docs about adding analytics and putting the exposed JS functions but otherwise this is ready for review

2024-06-18 20:50 UTC, wes-otf commented
@frjo I swapped the analytics toggle for the same buttons that are on the front page as suggested - definitely makes more sense.

2024-06-19 06:28 UTC, frjo requested changes
Some minor things. Looks really good overall now.

2024-06-19 06:28 UTC, frjo commented on hypha/cookieconsent/templates/includes/banner.html
> +                            <span class="text-green-500">Always enabled.</span>
This green has a low contrast against the blue background. Maybe make it bold white instead?

<img width="962" alt="Skärmavbild 2024-06-19 kl  08 16 25" src="https://github.com/HyphaApp/hypha/assets/191392/73053738-1354-4999-83ab-5b0a2227000d">

2024-06-19 06:28 UTC, frjo commented on hypha/cookieconsent/templates/includes/banner.html
> +                        <p>This Website uses cookies.  Below you can select the categories of cookies to allow when you use our website and services.  For more information, please see our Privacy Pol
Please make this text translatable.

2024-06-19 06:28 UTC, frjo commented on hypha/cookieconsent/templates/includes/banner.html
> +                        <p>This Website uses cookies.  Below you can select the categories of cookies to allow when you use our website and services.  For more information, please see our Privacy Pol
I think only the last sentence is not needed. Let people add additional info in the text you edit in the settings.

2024-06-19 13:13 UTC, wes-otf commented
Thanks for that feedback! Totally agreed with all. Bold white definitely makes it stand out quite a bit more.
![Screenshot 2024-06-19 at 09 12 53](https://github.com/HyphaApp/hypha/assets/145372368/af6d20e4-b2aa-46d8-899b-43fdef35e033)

2024-06-19 13:29 UTC, frjo approved these changes

2024-07-02 20:43 UTC, wes-otf commented
@frjo #3994 breaks the styling of this - should I rebase onto that?

2024-07-03 06:04 UTC, frjo commented
@wes-otf Most likely only the new media-query breakpoints needs updating.

2024-07-03 15:59 UTC, wes-otf commented
yeah it was, I rebased onto #3994 and all looks good now. This was user tested yesterday and aside from the media breakpoints all was good

2024-07-04 05:34 UTC, merged