Add invoice date to invoice and invoices lists and tables
HyphaApp/hypha pull request #4019
Opened 2024-06-28 11:35 UTC by sandeepsajan0

Fixes #3537 

![image](https://github.com/HyphaApp/hypha/assets/23638629/177ac9bd-796b-4459-8937-16142f24d168)

## Test Steps

 - [ ] …

2024-07-05 07:16 UTC, frjo commented
Migration conflict with another PR on test so we wait to test this for a bit.

2024-08-30 14:34 UTC, wes-otf commented
Just had a demo meeting with finance and they liked it! When the pay date is set via the update status modal, where is that info displayed? I couldn't find where that was listed after it was set.

2024-08-30 14:41 UTC, wes-otf commented
two other quick notes: 

1. do we need the timestamp on the `Invoice Date` field or could it only be the date (like the `Pay Date` field)? 
2. the `Update status` button formatting breaks when in the staff admin role, while for finance it looks fine. Not sure if this is a result of this PR or something else, though:
![Screenshot 2024-08-30 at 10 38 04](https://github.com/user-attachments/assets/c9c96941-43eb-4774-8768-01e7b9d56040)

2024-09-02 08:14 UTC, frjo commented
1. I think we can use `DateField` instead of `DateTimeField` for both `paid_date` and `invoice_date`.
2. @wes I think you was the "applicant" as well if you could see the delete button. According to the code only applicants see the delete button in the table.

https://github.com/HyphaApp/hypha/blob/1372124eb9f5d2a4d203515d7c35522039d3c217/hypha/apply/projects/templates/application_projects/includes/invoices.html#L47-L53

2024-09-02 08:16 UTC, frjo requested changes

2024-09-02 08:16 UTC, frjo commented on hypha/apply/projects/models/payment.py
> +    paid_date = models.DateTimeField(null=True, verbose_name=_("Paid date"))
I think we can use `DateField` for both these fields.

2024-09-12 06:11 UTC, frjo approved these changes

2024-09-12 06:12 UTC, merged