Add a reporting table for projects
HyphaApp/hypha pull request #4051
Opened 2024-07-12 17:47 UTC by bickelj

What a small line for such a large set of changes.  Those supporting changes include:

* Creating a view for the new Reporting Table
* Creating a current_report() method in report_config that is slightly differnt than current_report_due (see inline doc)
* Adding a ProjectQuerySet method that does some intense subquerying to be able to express the current_report in sql so that the status can be filtered against

Issue #4050`

## Note from the cherry-picker/integrator

I see that the summary tables for reports was removed from `apply/projects` and that the current dropdown in the main navigation header points to `apply/project/reports`. This new table appears under `apply/project/reporting` and is linked to in the original fork in which this change occurred. As for integration here, the question is: do we want to replace the original table or augment off to the side somehow? Where should the link to this new table live?

## Test Steps

URL is `apply/projects/reporting`.

 - [ ] Get a project to the reporting phase, and it should show up in the table
 - [ ] Filter the table by not started and make sure it shows up
 - [ ] Set the project's report due to various kinds, and the report due date in table should change correspondingly
 - [ ] Save a report as a draft, which should move it to in progress on the table
 - [ ] Filter the table by in progress to make sure it shows up!
 - [ ] Complete the report, which should move it to submitted status on the table
 - [ ] Filter the table by submitted to make sure it shows up.

2024-07-30 16:51 UTC, bickelj commented
@frjo Is this one ready for merge?

2024-07-31 07:52 UTC, frjo requested changes
What is the main task that this table makes possible that can not be done with the main project table?

Could we extend the project table instead?

Select2 and fancybox are both packages we are moving away from. A bit hesitant to add new code that uses them.

2024-07-31 07:52 UTC, frjo commented on hypha/apply/projects/tables.py
> +        verbose_name="Last Notified",
Please avoid title case. We have it in several places but are moving away from it.

2024-07-31 07:52 UTC, frjo commented on hypha/apply/projects/urls.py
> +    path("reporting/", ReportingView.as_view(), name="reporting"),
Moving this down to "reports/" might look nicer.

2024-10-08 11:09 UTC, frankduncan commented
This table is specifically for monitoring the status of reports.  When projects get through the main phases and into the reporting phase, our client needed a way to manage, filter, and sort based on the status of those reports.  So this adds a number of columns not on the original project table specifically having to do with whether reports are up to date, etc.

We felt that this table should be separate, just for the user experience.  There would be a number of new columns that would need to be prefixed with "Report <X>" if we added them to the project table, rather than having a view into just the status of the various project reports.  Furthermore, the project table might get a bit busy.

2024-11-13 09:32 UTC, frjo approved these changes

2024-11-18 21:58 UTC, wes-otf commented
Works well! I might write up an issue to put this as a view under Reports thought so we don't have menu items for `Reports` & `Reporting`, I could see that being mildly confusing to users. Let me know what you think @frjo

2024-11-19 06:31 UTC, merged

2024-11-19 07:26 UTC, frjo commented
@wes-otf I agree that the two report items in the menu can be confusing. Please create a PR with your suggestion, sounds better.