Add confirm message when exporting submission data as csv file
HyphaApp/hypha pull request #4118
Opened 2024-08-29 12:28 UTC by sandeepsajan0

Fixes #4058 

## Test Steps

 - [ ] …

2024-09-09 10:13 UTC, theskumar requested changes

2024-09-09 10:13 UTC, theskumar commented on hypha/apply/funds/templates/funds/includes/table_filter_and_search.html
>                          role="button"
This could use translated string.

2024-09-09 14:05 UTC, wes-otf approved these changes

2024-10-01 05:58 UTC, theskumar commented
@sandeepsajan0 I think after adding the translations marker, this PR is good to merge.

2024-10-20 09:23 UTC, merged