Speed up CI
HyphaApp/hypha pull request #4164
Opened 2024-10-15 12:18 UTC by theskumar

Check the individual commits for more info, for now.

2024-10-19 16:30 UTC, frjo requested changes
Looks really neat! One minor comment.

2024-10-19 16:30 UTC, frjo commented on Makefile
> +PIP := $(shell command -v pip 2> /dev/null || echo 'uv pip')
Will not `command -v pip` be true as default on most systems? Can we check for `uv` instead and use `pip` only if it is not installed?

2024-10-19 18:26 UTC, theskumar commented on Makefile
> +PIP := $(shell command -v pip 2> /dev/null || echo 'uv pip')
It make sense, on my machine, the pip was missing instead pip3 was available as global. `pip` get available only in the virtualenv. 

This check won't be needed when/if we move to using `uv` with dependencies in pyproject. At that point we would always have `uv` and then run `uv sync` all the time.

2024-10-19 19:12 UTC, frjo approved these changes

2024-10-20 09:53 UTC, frjo commented
From a reset test run on current hypha-ci:

![Skärmavbild 2024-10-20 kl  11 48 53](https://github.com/user-attachments/assets/d2e89c78-77a9-41e2-bb17-a283ac39be12)

From the new hypha-ci in this PR on the test branch:

![Skärmavbild 2024-10-20 kl  11 49 39](https://github.com/user-attachments/assets/ac84aa1e-e8cc-4c7c-945a-b4e8f7f0995d)

I know from experience that the times to run these GitHub actions varies quite a bit but a two minuts save, -30%, is nice to see indeed.

2024-10-21 07:10 UTC, theskumar commented
I agree, they are very good numbers and on a regular run it should finish around 3mins (-50%), which is similar to the time taken by CodeQL. 

This allows to write more tests without worrying about test timing for a while.

2024-10-21 11:47 UTC, merged