Remove AwaitingReview view, give reviewer access to submission all
HyphaApp/hypha pull request #4209
Opened 2024-11-11 14:31 UTC by frjo

Fixes # 4146

2024-11-12 07:39 UTC, theskumar requested changes

2024-11-12 07:39 UTC, theskumar commented on hypha/apply/dashboard/templates/dashboard/includes/submissions-waiting-for-review.html
> +            <a href="{{ awaiting_reviews.url }}?reviewers={{ request.user.pk }}">{% trans "Show all" %}</a>
This doesn't work, I believe this should go to submission all page, with something like `?query=reviewers:@me is:open`, keeping the query intensionally composable. 


![Screenshot 2024-11-12 at 7  02 53@2x](https://github.com/user-attachments/assets/1ad8ba70-2e1f-4145-8d3b-5aa706a1c647)

2024-11-12 07:39 UTC, theskumar commented on hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
> +                    <a href="{{ my_reviewed.url }}?reviewers={{ request.user.pk }}&reviewedby=me">{% trans "Show all" %}</a>
I would recommend coming up with another language in the query, something on the line of: 

`reviewed-by:@me` and `reviewed-by:<user_id>`

2024-11-12 07:39 UTC, theskumar commented on hypha/apply/funds/templates/funds/includes/submission-table-row.html
> +{% load i18n workflow_tags querystrings %}
can we use `{% load show_applicant_identity from workflow_tags %}` to make it more explicit?

2024-11-12 07:39 UTC, theskumar commented on hypha/apply/funds/views_all.py
> +
```suggestion
        else:
            qs = qs.in_review_for(request.user)

    if "reviewed-by" in search_filters:
        if "@me" in search_filters["reviewed-by"]:
            qs = qs.reviewed_by(request.user)

```

2024-11-12 07:39 UTC, theskumar commented on hypha/apply/funds/views_all.py
> +
Make `reviewed-by:@me` an independent filter.

2024-11-12 09:52 UTC, frjo commented on hypha/apply/funds/templates/submissions/all.html
> +                hx-get="{% url "apply:submissions:list" %}?query=reviewer:@me"
@theskumar Looked like the double "href" was a mistake but it still worked?

2024-11-12 09:54 UTC, frjo commented
@theskumar Implemented your suggestion and made some other changes. Please take a new look.

2024-11-18 21:16 UTC, wes-otf commented
Also could we swap `overflow-x-scroll` -> `overflow-x-auto` here?:

https://github.com/HyphaApp/hypha/blob/9aca48b043ac4c11b8814458e9e7af2239847a27/hypha/apply/funds/templates/submissions/partials/submissions-inline.html#L11

that'll get rid of that gap between the tab & show all

2024-11-18 21:17 UTC, wes-otf commented
Other than those two small things this is good to go! A lot more slick!

2024-11-19 07:18 UTC, merged