Fix submission with "invite to proposal" status stuck in draft if language is not english
HyphaApp/hypha pull request #4220
Opened 2024-11-16 15:21 UTC by theskumar

The current implementation tries to find the transition based on the `name` property of the transitions available. The name of the transition is a translated string so while submitting a proposal the key "submit" from the `request.POST` could not be found in the available transition.

This PR updates the logic to fetch the transition target, by searching through the newly added marker on when to auto transition if the application is submitted.

Fixes #4211 

See https://github.com/HyphaApp/hypha/pull/4220/commits/e6656d62f6db57426bb15f298127c106ea4f6397 for patch.

## Test Steps

 - Update the settings `LANGUAGE_CODE` to `sv`
 - For a fund with "Concept and Proposal" workflow, create a submission and approve the concept.
 - Now, logic as applicant and try to submit the "Proposal" while you application is in "Invited for Proposal" stage
 - The application should go through
 - If this patch is not applied, the status won't update.

2024-11-16 16:24 UTC, frjo requested changes
This fixes the invite for proposal draft.

It does not seem to fix an initial draft, when e.g. an applicant apply for a lob or content note and begin with saving as draft.

2024-11-16 16:24 UTC, frjo commented on hypha/apply/funds/views.py
> +                    not (revision or submitting_proposal)
`submitting_proposal` will always be true inside `if submitting_proposal:`

2024-11-16 17:22 UTC, theskumar commented on hypha/apply/funds/views.py
> +                    not (revision or submitting_proposal)
Nice catch.

2024-11-16 17:25 UTC, theskumar commented
> Excellent progress! This fixes the invite for proposal draft.
> 
> It does not seem to fix an initial draft, when e.g. an applicant apply for a lab or content note and begin with saving as draft.

It is a oversight from my side, the latest should work. https://github.com/HyphaApp/hypha/pull/4220/commits/def0e76759a2eec577d57cdb8218a2fdb402bb8b

2024-11-16 17:32 UTC, theskumar commented
Test are failing, I'll take a deeper look.

2024-11-16 17:35 UTC, frjo approved these changes

2024-11-18 03:48 UTC, theskumar commented
After carefully reviewing, I realized that the application auto-advances to the next `phase` at different phases, and there could be multiple phases it can transition to when the application is at a specific phase, say `more info required` phase. Therefore, we need an explicit marker to decide:

1. Whether to auto advance or not, if the user submits the application. 
2. which target phase to pick when the user submit a application. 

The current fix, while functional, has an issue where it will always transition to the first available transition at that Phase.

I think we can solve this we need to update the workflow spec itself, that enables to deterministically know above two:  

1. Remove the translation marker,  on the "Submit" display name, I believe it's not displayed in the UI anywhere.
2. Introduce a new custom property on the target phase that indicates whether to auto-advance to this phase if the user submits the application at the source phase.

![Screenshot 2024-11-18 at 3  32 04@2x](https://github.com/user-attachments/assets/6778e38c-cffb-467b-9c22-33583f783b62)

@frjo @wes-otf Any preference on the (1) or (2). My take would be to go for an explicit custom marker, even though it's little verbose, for the shake of clarity.

2024-11-18 04:22 UTC, sandeepsajan0 commented
@theskumar I am not sure about the best approach but what do you think about having a predefined method that can return both types of keys as translated(in same lang) and we can call that method wherever in code we are comparing these keys. 
Ex:  
```
def translated_keys(post_keys, transition_keys):
    ......
    return translated_post_keys, translated_transition_keys

```

2024-11-18 07:42 UTC, theskumar commented
> @theskumar I am not sure about the best approach but what do you think about having a predefined method that can return both types of keys as translated(in same lang) and we can call that method wherever in code we are comparing these keys like [here](https://github.com/HyphaApp/hypha/pull/4220/files#diff-cf22f20205f278f19b4b22cd6e5decb2f0a9548aba7e3a779b7ff9e0b1d117faL1406). Ex:
> 
> ```
> def translated_keys(post_keys, transition_keys):
>     ......
>     return translated_post_keys, translated_transition_keys
> ```

Thank for the input, initial tried getting the untranslated version of the `display` but it looks by the time it reaches here as a key of the dictionaries, this is already translated, and it make sense as the translated string will be needed for hashing in in the dict. 

I'm in a opinion that we should not be doing comparison on the basis of translated strings. 

Also, since the `post.keys` are never marked as translatable, you can't get equivalent translated string reliably.

2024-11-18 08:14 UTC, frjo commented
I think option two is best.

I agree that we should never compare strings that might be translated.

I see no other places but in this `form_valid()` function that we do this check. Correct?

Progressing when saving a submission should only happen when submitting a draft and when submitting a "More information is needed".

Having something explicit in the workflows for these two statuses would make it more clear what is happening.

2024-11-18 12:41 UTC, theskumar commented
> I see no other places but in this `form_valid()` function that we do this check. Correct?

Yes, that's when we check if the "Submit" action is present in the targets and then `perform_transition` to that phase.

I'll check other places as well, but it doesn't seem it should have been used. (If we are using translated string for comparisons at other places, that would probably be another ticket for us to go over)

---

For the custom route, I'll need to modify some parts of how the phases and transitions are initialized, but it shouldn't be too complicated. I'll be updating the this PR. 

_PS: Down the road, we must split this workflow file into different module. I see two `Request` object defined in the same file, one related to Stage and another for Workflow._

2024-11-20 06:19 UTC, theskumar commented
Updated the logic to add new marker in the workflow definition indicating this particular phase to pick when the user submits the application and then auto transition to it.

2024-11-20 13:57 UTC, frjo approved these changes
Works nicely for me.

2024-11-25 20:50 UTC, wes-otf commented
worked great, really nice work @theskumar!

2024-11-25 20:57 UTC, merged