Separate SOW & PAF form editing
HyphaApp/hypha pull request #4261
Opened 2024-12-06 21:08 UTC by wes-otf

Fixes #4204. Moves the SOW out into it's own form when editing. This also removes the `user_has_updated_details` attribute in favor of using a property for both the project form & SOW that checks the field_data on the respective form. This allows for tracking of the project form & SOW independently. 

Also a few small aesthetic changes bundled in, like margin additions & hiding of submission attachments sidebar when there's none.

## Screenshots

*appearance when first creating a project*
<img width="939" alt="Screenshot 2024-12-06 at 16 07 24" src="https://github.com/user-attachments/assets/101729c8-5072-4179-8b1a-5dff02eda822">

*appearance after editing both forms*
<img width="939" alt="Screenshot 2024-12-06 at 16 04 29" src="https://github.com/user-attachments/assets/2b55911d-cdf7-47cc-92b3-7aa654278d1e">

## Test Steps

 - [ ] When viewing the details of a project with both a Project Form & SOW, ensure that both appear under `Project documents`.
 - [ ] Confirm that both can be edited, saved, and viewed on their own
 - [ ] Confirm that when creating a project from a fund that has a Project Form & SOW, a todo list item is created for both

2024-12-07 10:02 UTC, frjo requested changes
This is a good change, it was a bit of a hack having them merged in the first place.

Found some minor issues.

How will the SOW not fit in to the approval workflow?

2024-12-07 10:02 UTC, frjo commented on hypha/static_src/sass/components/_docs-block.scss
> +            margin-left: auto;
Please use `margin-inline-start` instead.

2024-12-07 10:02 UTC, frjo commented on hypha/apply/projects/views/project.py
> +    PROJECT_SUBMIT_PF,
As a machine name we use "PAF" everywhere so I think it is best to stick with that.

I do not mind changing it to "PF" or "PROJECT_FORM" etc. but it should be done everywhere.

2024-12-07 10:02 UTC, frjo commented on hypha/apply/projects/templates/application_projects/project_sow_detail.html
> +                        <div class="simplified__paf_answers">
This class was removed in https://github.com/HyphaApp/hypha/pull/4196.

2024-12-11 14:54 UTC, wes-otf commented
all that left is getting these tests passing - a bit of a battle because my flag uses the project's `form_data`, but that won't get written unless a valid FormFieldBlock wrapped in a StreamValue is passed in the `save` method kwargs. it's giving me a hard time when I try to mock it

https://github.com/HyphaApp/hypha/blob/acdbea36177c90adb5cf24a7a61dd6d527a33f9e/hypha/apply/projects/forms/project.py#L137-L143

2024-12-11 15:46 UTC, frjo commented on hypha/apply/projects/templates/application_projects/project_sow_detail.html
> +                        <div class="simplified__paf_answers">
Are not the "rich-text rich-text--answers" ok to use? We use them in most other places when we render streamfields.

2024-12-11 15:47 UTC, frjo commented on hypha/apply/projects/views/project.py
> +    PROJECT_SUBMIT_PF,
Ping

2024-12-11 15:47 UTC, frjo commented on hypha/static_src/sass/components/_docs-block.scss
> +            margin-left: auto;
ping

2024-12-11 15:52 UTC, frjo commented
@wes-otf How vital is the test? We could remove it.

2024-12-11 16:19 UTC, wes-otf commented
@frjo Yeah that sounds good - I don't think it's vital as it'd really just be checking if `form_data` is an empty dict. I tossed it and added your suggestions

2024-12-11 18:34 UTC, frjo approved these changes

2024-12-12 22:10 UTC, wes-otf commented
grabbed some final bug fixed but should be ready to be deployed to test now @frjo

2024-12-16 12:58 UTC, frjo commented
@wes-otf When I download a SOW at http://apply.hypha.test:9001/apply/projects/4/sow/ no fields are added to the exports. I guess something changes regarding getting the fields?

When I test the main branch locally it seems to work as it should.

2024-12-16 21:55 UTC, wes-otf commented
@frjo great catch! my logic was copy & pasted, checking `self` rather than `project` - also removed some mentions of the SOW in the PAF export.

2024-12-17 08:09 UTC, frjo commented
Deploying the latest to test now.

2024-12-17 18:21 UTC, frjo commented
Can confirm that the bug in sow exports are now fixed. Looks all good to me.

2024-12-17 18:36 UTC, wes-otf commented
@frjo thanks for testing - I think it's ready to go then! I did more testing on my end too and didn't see anything

2024-12-17 18:58 UTC, merged