Update the UI to switch user aka become user
HyphaApp/hypha pull request #4294
Opened 2024-12-18 09:13 UTC by theskumar

Fixes #4131 

- Rename to "switch user"
- Can switch from the user menu
- Switch to choices.js from Select2
- Update the hijacked view, shows an alert at the top

![Screenshot 2024-12-18 at 9  22 59@2x](https://github.com/user-attachments/assets/7fbd39ab-5f39-481c-81d4-1d7e72f91f08)
![Screenshot 2024-12-18 at 9  23 31@2x](https://github.com/user-attachments/assets/eb5682c2-3b5c-45a3-9fee-f4167a520f0a)
![Screenshot 2024-12-18 at 9  23 53@2x](https://github.com/user-attachments/assets/7c39254b-e43c-4507-8ef9-fbd28cf334bf)
![Screenshot 2024-12-18 at 9  24 19@2x](https://github.com/user-attachments/assets/960303b8-b544-4c8d-aac2-0d08f6019133)

2024-12-18 10:26 UTC, frjo commented
This looks and works really nicely! Will be a pleasure to use when we get it deployed.

I have one issue. The function `get_become_user_choices()` is slow. I think `get_role_names()` takes up most of the time.

With 4000 users it takes around three (3) seconds. I think OTF has even more users. This should not be used in production but even test data can have a lot of users.

Possible to speed it up a bit, showing the role in the list is useful so good if we can keep that. Maybe caching the list would work?

2024-12-18 10:27 UTC, frjo requested changes

2024-12-18 10:27 UTC, frjo commented on hypha/apply/users/forms.py
> +                    f'<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">{str(g)}</span>'
This seems not to show up in the dialog select  list?

2024-12-18 10:52 UTC, theskumar commented
> I have one issue. The function get_become_user_choices() is slow. I think get_role_names() takes up most of the time.

> With 4000 users it takes around three (3) seconds. I think OTF has even more users. This should not be used in production but even test data can have a lot of users.

Will look into it.

2024-12-18 15:11 UTC, wes-otf commented
This is super slick! I really like the banner as opposed to the pop up window that you need to dismiss every time you reload the page. Nice improvement!

2024-12-20 09:09 UTC, theskumar commented on hypha/apply/users/forms.py
> +                    f'<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">{str(g)}</span>'
This doesn't seem be supported, removed it.

2024-12-20 09:11 UTC, theskumar commented
@frjo Updated the query to fetch the groups. It should always come down to 2 queries now. That said, if we face issue in the test site, we can switch to fetching the options as you type, via a search api.

2024-12-20 09:12 UTC, theskumar commented
The new implementation of `user.is_*` checks will improve the performance overall at multiple places.

2024-12-20 14:33 UTC, frjo approved these changes
Now the load time is more or less instant and works equally well in other respects.

2025-01-02 16:22 UTC, wes-otf commented
@frjo has this been deployed to test?

2025-01-02 20:11 UTC, frjo commented
Nope, forgot to push. Deploying now.

2025-01-03 16:37 UTC, merged